### PR TITLE
Changing the structure to records types and setting the environment for ifort

### PR DESCRIPTION
**Pull request by paulschou**

### CODE REVIEW

**Comment by strow** [comment]
Paul,

Lot's of changes, can you give me a little more info on the details.  Looks like a lot of file name changes for the coefficient files?   What is type vs record?

**Comment by strow** [comment]
Paul, could you put this into a branch, and we merge the branch into sarta?  You think that is an OK idea or not?

**Comment by paulschou** [comment]
I didn't remove or add any code, all I did was make it f90 compliant. 
The Make file sets the set of coefficient files loaded when you specify 
the template file to use. 'Type' is the f90 replacement of the F77 'Record'.

strow wrote:

**Comment by paulschou** [comment]
It's hard to justify this as a new branch as this is a code syntax 
change. I spent a bit of the day cross compiling the libdf and hopefully 
hdf4 into the intel phi architecture.

strow wrote:

**Pull request merged**
